ALTER TABLE items ADD COLUMN item_type TEXT NOT NULL DEFAULT 'RAW' CHECK (item_type IN ('RAW', 'BULK_POWDER', 'PACKING_MATERIAL', 'FINISHED_GOOD'));
ALTER TABLE items ADD COLUMN base_unit TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN item_subtype TEXT;

UPDATE items
SET item_type = CASE UPPER(TRIM(category))
    WHEN 'RAW' THEN 'RAW'
    WHEN 'BULK_POWDER' THEN 'BULK_POWDER'
    WHEN 'PACKING_MATERIAL' THEN 'PACKING_MATERIAL'
    WHEN 'FINISHED_GOOD' THEN 'FINISHED_GOOD'
    ELSE 'RAW'
END;

UPDATE items
SET base_unit = COALESCE(NULLIF(TRIM(unit), ''), 'unit');
